apiVersion: batch/v1
kind: Job
metadata:
  name: create
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: brightcove-docker-secret
      containers:
        - name: create
          image: lfgarcia10/kubernetes:latest
          command: ["bundle", "exec", "rake"]
          args: ["db:create"]
          envFrom:
            - configMapRef:
                name: postgres-config
