apiVersion: v1
kind: Pod
metadata:
  name: terminal
spec:
  containers:
    - name: terminal
      image: lfgarcia10/kubernetes-test:latest
      command: ["sleep"]
      args: ["infinity"]
      envFrom:
        - configMapRef:
            name: postgres-config